SUBDIRS=bitonic_sort connected_comp detect_edges dilation dutch_flag erosion \
floyd_warshall gcd merge_sort prim toupper transitive_closure kruskal
clean:
	$(foreach dir, $(SUBDIRS), make -C $(dir) force_clean;)	
