SUBDIRS=array_loop_nonuniform_ldst       dutch_flag           gcd                 regexp           symbolic_arg     unaligned_loadstore \
array_loop_uniform_ldst          erosion              get_sign                 symbolic_malloc \
diamond_inside_loop              fibonacci_recursive  if_then_inside_loop  merge           simple_dataflow  symbolic_vaarg \
diamond_inside_loop_with_verify  function_call        Makefile             merge_sort      sort             two_loops detect_edges toupper abs_diff \
false_positive
clean:
	$(foreach dir, $(SUBDIRS), make -C $(dir) clean;)	
